// <auto-generated />
using System;
using Jira.Querying.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Jira.Querying.Migrations
{
    [DbContext(typeof(IssuesCacheContext))]
    [Migration("20191013144742_CachedIssue")]
    partial class CachedIssue
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Jira.Querying.Sqlite.CachedIssueDb", b =>
                {
                    b.Property<string>("Key")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("Created");

                    b.Property<int?>("OriginalEstimate");

                    b.Property<string>("Resolution");

                    b.Property<DateTime?>("Resolved");

                    b.Property<string>("Status");

                    b.Property<int?>("StoryPoints");

                    b.Property<int?>("TimeSpent");

                    b.Property<string>("Title");

                    b.Property<string>("Type");

                    b.Property<DateTime?>("Updated");

                    b.HasKey("Key");

                    b.ToTable("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
