// <auto-generated />
using System;
using Jira.Querying.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Jira.Querying.Migrations
{
    [DbContext(typeof(IssuesCacheContext))]
    [Migration("20200419132136_IssueProject")]
    partial class IssueProject
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Jira.Querying.Sqlite.CachedIssueDb", b =>
                {
                    b.Property<string>("Key")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("Created");

                    b.Property<int?>("OriginalEstimate");

                    b.Property<string>("Project")
                        .IsRequired();

                    b.Property<string>("Resolution");

                    b.Property<DateTime?>("Resolved");

                    b.Property<string>("Status");

                    b.Property<int?>("StoryPoints");

                    b.Property<int?>("TimeSpent");

                    b.Property<string>("Title");

                    b.Property<string>("Type");

                    b.Property<DateTime?>("Updated");

                    b.HasKey("Key");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("Jira.Querying.Sqlite.CachedIssueDb", b =>
                {
                    b.OwnsMany("Jira.Querying.Sqlite.CachedIssueStatusChangeDb", "StatusChanges", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd();

                            b1.Property<DateTime>("ChangeTime");

                            b1.Property<string>("IssueKey")
                                .IsRequired();

                            b1.Property<string>("State");

                            b1.HasKey("Id");

                            b1.HasIndex("IssueKey");

                            b1.ToTable("CachedIssueStatusChangeDb");

                            b1.HasOne("Jira.Querying.Sqlite.CachedIssueDb")
                                .WithMany("StatusChanges")
                                .HasForeignKey("IssueKey")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
