// <auto-generated />
using System;
using Jira.Querying.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Jira.Querying.Migrations
{
    [DbContext(typeof(IssuesCacheContext))]
    partial class IssuesCacheContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Jira.Querying.CachedIssueDb", b =>
                {
                    b.Property<string>("Key")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("Created");

                    b.Property<DateTime?>("Updated");

                    b.HasKey("Key");

                    b.ToTable("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
